### PR TITLE
Bulk Big fixing from PE Dry Run

### PR DESCRIPTION
**Pull request by Hackin7**
Bulk bugfixing for v2.1. Due to time constraints, I've combined it into 1 PR, to get the exact fixes, might be easier to check commit by commit

### CODE REVIEW

**Comment by Hackin7** [comment]
https://github.com/AY2425S1-CS2113-W12-3/tp/issues/155

**Comment by Hackin7** [comment]
Fixed https://github.com/AY2425S1-CS2113-W12-3/tp/issues/147 and tested

**Comment by Hackin7** [comment]
Fixed https://github.com/AY2425S1-CS2113-W12-3/tp/issues/128 in UG

**Comment by Hackin7** [comment]
https://github.com/AY2425S1-CS2113-W12-3/tp/issues/142
https://github.com/AY2425S1-CS2113-W12-3/tp/issues/167

Documented in UG

**Comment by Hackin7** [comment]
https://github.com/AY2425S1-CS2113-W12-3/tp/issues/160
https://github.com/AY2425S1-CS2113-W12-3/tp/issues/142

**Comment by Hackin7** [comment]
https://github.com/AY2425S1-CS2113-W12-3/tp/issues/158

**Comment by Hackin7** [comment]
So apparently I have reached the max number of issues possible to be linked so that's it for this PR

**Comment by Hackin7** [comment]
- https://github.com/AY2425S1-CS2113-W12-3/tp/issues/143

**Comment by Hackin7** [comment]
- https://github.com/AY2425S1-CS2113-W12-3/tp/issues/143

**Comment by Hackin7** [comment]
- https://github.com/AY2425S1-CS2113-W12-3/tp/issues/162

**Comment by Hackin7** [comment]
- https://github.com/AY2425S1-CS2113-W12-3/tp/issues/168
  - https://github.com/AY2425S1-CS2113-W12-3/tp/issues/135
  - https://github.com/AY2425S1-CS2113-W12-3/tp/issues/134
  - https://github.com/AY2425S1-CS2113-W12-3/tp/issues/138

**Review by KHsienKit — APPROVED** [review]
Looks good

**Pull request merged**
