### PR TITLE
V2.1 Fixes

### LINKED ISSUE #164: [PE-D][Tester E] Display of footboxes in sequence diagrams decision
Should footboxes be shown for sequence diagrams?

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: wahkia/ped#12

### PR DESCRIPTION
**Pull request by KHsienKit**
#164 DG Sequence diagram fixed

### CODE REVIEW

**Comment by KHsienKit** [comment]
#153 Added more details about the /recur flag to UG

**Comment by KHsienKit** [comment]
#125 Fixed

**Comment by KHsienKit** [comment]
#146 Updated DG on test methods for recurring expenses

**Comment by KHsienKit** [comment]
#137 Fix bug where add a recurring expense did not add the equivalent normal expense

**Comment by Hackin7** [comment]
LGTM!

**Review by Hackin7 — COMMENTED** [review]
The code looks good to me, but more testing will be done soon

**Review by Hackin7 — APPROVED** [review]
The code looks good to me, but more testing will be done soon

**Pull request merged**
